import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import { Client } from 'pg';
import { normalizeHeadword, validateRow, InventoryRow } from './inventory';
import { stableDsdEntryId } from './ai/inventory-planner';

const EXPECTED_COUNT = 475_153;
function arg(name: string): string | undefined { const i = process.argv.indexOf(`--${name}`); return i >= 0 ? process.argv[i + 1] : undefined; }
function required(name: string): string { const value = arg(name)?.trim(); if (!value) throw new Error(`--${name} is required`); return value; }
function csv(value: unknown): string { const text = String(value ?? ''); return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }

export interface HeadwordQuarantine { headword: string; normalized: string; reasons: string[] }

function inventoryRow(headword: string, date: string, priority: number): InventoryRow {
  return {
    dsd_entry_id: stableDsdEntryId(headword), headword, part_of_speech_expectation: 'infer',
    dsd_priority: String(priority), dsd_band: 'legacy-headword-free-dictionary',
    product_rationale: 'Included as a lookup headword; all expressive dictionary content is newly generated by DSD.',
    author_contributor_id: 'DSD-O-001', authored_date: date,
    inventory_evidence_id: 'EV-DSD-LEGACY-HEADWORDS-ONLY-20260811',
    declaration_id: 'EV-DSD-LEGACY-HEADWORDS-ONLY-DECLARATION-20260811',
  };
}

export function buildLegacyHeadwordRows(headwords: string[], date: string): {
  rows: InventoryRow[]; quarantine: HeadwordQuarantine[];
} {
  const unique = new Map<string, string>(); const quarantine: HeadwordQuarantine[] = [];
  for (const raw of headwords) {
    const normalized = normalizeHeadword(raw);
    if (!normalized.headword) { quarantine.push({ headword: raw, normalized: '', reasons: ['empty headword'] }); continue; }
    if (unique.has(normalized.headwordNormalized)) {
      quarantine.push({ headword: normalized.headword, normalized: normalized.headwordNormalized,
        reasons: [`duplicate normalized headword '${normalized.headword}'`] });
      continue;
    }
    unique.set(normalized.headwordNormalized, normalized.headword);
  }
  const rows: InventoryRow[] = [];
  for (const [normalized, headword] of [...unique.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const row = inventoryRow(headword, date, rows.length + 1);
    const reasons = validateRow(row, rows.length + 2);
    if (reasons.length) quarantine.push({ headword, normalized, reasons });
    else rows.push(row);
  }
  return { rows, quarantine };
}

async function main(): Promise<void> {
  if (process.argv[2] !== 'export') throw new Error('usage: legacy-headword-inventory.ts export --output FILE --quarantine FILE --manifest FILE --date YYYY-MM-DD');
  const rawUrl = process.env.LEGACY_HEADWORD_DATABASE_URL?.trim();
  if (!rawUrl) throw new Error('LEGACY_HEADWORD_DATABASE_URL is required');
  const url = new URL(rawUrl);
  if (decodeURIComponent(url.username) !== 'dsd_headword_reader') throw new Error('LEGACY_HEADWORD_DATABASE_URL must use dsd_headword_reader');
  const date = required('date'); if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error('--date must be YYYY-MM-DD');
  const client = new Client({ connectionString: rawUrl }); await client.connect();
  let values: string[];
  try {
    const result = await client.query('SELECT headword FROM dsd_compliance.headword_inventory_input');
    if (result.fields.length !== 1 || result.fields[0].name !== 'headword') throw new Error('headword view contract widened unexpectedly');
    values = result.rows.map((row) => String(row.headword));
  } finally { await client.end(); }
  if (values.length !== EXPECTED_COUNT) throw new Error(`expected ${EXPECTED_COUNT} source rows, got ${values.length}`);
  const built = buildLegacyHeadwordRows(values, date);
  if (!built.rows.length) throw new Error('no headwords passed the inventory boundary');
  if (built.rows.length + built.quarantine.length !== EXPECTED_COUNT) throw new Error('inventory reconciliation failed');
  const output = path.resolve(process.cwd(), required('output')); const manifestFile = path.resolve(process.cwd(), required('manifest'));
  const quarantineFile = path.resolve(process.cwd(), required('quarantine'));
  if ([output, manifestFile, quarantineFile].some(fs.existsSync)) throw new Error('refusing to overwrite inventory, quarantine, or manifest');
  fs.mkdirSync(path.dirname(output), { recursive: true });
  const columns = ['dsd_entry_id','headword','part_of_speech_expectation','dsd_priority','dsd_band','product_rationale',
    'author_contributor_id','authored_date','inventory_evidence_id','declaration_id'];
  const content = [columns, ...built.rows.map((row) => columns.map((column) => (row as any)[column]))]
    .map((row) => row.map(csv).join(',')).join('\n') + '\n';
  fs.writeFileSync(output, content, { flag: 'wx', mode: 0o600 });
  const quarantineContent = JSON.stringify({ version: 1, source_row_count: values.length,
    quarantined_count: built.quarantine.length, entries: built.quarantine }, null, 2) + '\n';
  fs.writeFileSync(quarantineFile, quarantineContent, { flag: 'wx', mode: 0o600 });
  const manifest = { version: 1, inventory_mode: 'legacy_headwords_only', legacy_inventory_used: true,
    expressive_legacy_content_used: false, source_row_count: values.length, selected_row_count: built.rows.length,
    quarantined_row_count: built.quarantine.length,
    inventory_sha256: crypto.createHash('sha256').update(content).digest('hex'),
    quarantine_sha256: crypto.createHash('sha256').update(quarantineContent).digest('hex'),
    excluded_legacy_fields: ['id','part_of_speech','definition_en','definition_vi','example_en','example_vi','rank','ipa','audio'] };
  fs.writeFileSync(manifestFile, JSON.stringify(manifest, null, 2) + '\n', { flag: 'wx', mode: 0o600 });
  console.log(JSON.stringify({ output, quarantine: quarantineFile, manifest: manifestFile, ...manifest }, null, 2));
}
if (require.main === module) main().catch((error) => { console.error(error.message); process.exit(1); });
